// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/ui/AdminLayout.vue')['default']
    CartTable: typeof import('./src/components/cart/CartTable.vue')['default']
    Header: typeof import('./src/components/ui/Header.vue')['default']
    OrderForm: typeof import('./src/components/orders/OrderForm.vue')['default']
    OrdersTable: typeof import('./src/components/orders/OrdersTable.vue')['default']
    PublicLayout: typeof import('./src/components/ui/PublicLayout.vue')['default']
  }
}

export { }
