// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/ui/AdminLayout.vue')['default']
    AuthLayout: typeof import('./src/components/ui/AuthLayout.vue')['default']
    CartTable: typeof import('./src/components/cart/CartTable.vue')['default']
<<<<<<< HEAD
=======
    CartTable2: typeof import('./src/components/cart/CartTable2.vue')['default']
>>>>>>> primevue
    Dialog: typeof import('./src/components/ui/Dialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/ui/Header.vue')['default']
<<<<<<< HEAD
=======
    Header2: typeof import('./src/components/ui/Header2.vue')['default']
>>>>>>> primevue
    OrderForm: typeof import('./src/components/orders/OrderForm.vue')['default']
    OrdersTable: typeof import('./src/components/orders/OrdersTable.vue')['default']
    PublicLayout: typeof import('./src/components/ui/PublicLayout.vue')['default']
  }
}

export { }
